RailsDocket/config/routes.rb
RailsDocket::Application.routes.draw do
  resources :patentcases

  resources :clientcases

  resources :billings

  resources :firms

  resources :caseevents

  resources :cases

  resources :clients

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

RailsDocket/app/models/firm.rb
class Firm < ActiveRecord::Base
end

RailsDocket/app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @firms }
    end
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
    @firm = Firm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @firm }
    end
  end

  # GET /firms/new
  # GET /firms/new.json
  def new
    @firm = Firm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @firm }
    end
  end

  # GET /firms/1/edit
  def edit
    @firm = Firm.find(params[:id])
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(params[:firm])

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, :notice => 'Firm was successfully created.' }
        format.json { render :json => @firm, :status => :created, :location => @firm }
      else
        format.html { render :action => "new" }
        format.json { render :json => @firm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /firms/1
  # PUT /firms/1.json
  def update
    @firm = Firm.find(params[:id])

    respond_to do |format|
      if @firm.update_attributes(params[:firm])
        format.html { redirect_to @firm, :notice => 'Firm was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @firm.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm = Firm.find(params[:id])
    @firm.destroy

    respond_to do |format|
      format.html { redirect_to firms_url }
      format.json { head :ok }
    end
  end
end

RailsDocket/app/helpers/firms_helper.rb
module FirmsHelper
end

RailsDocket/app/views/firms/_form.html.erb
<%= form_for(@firm) do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :metatype %><br />
    <%= f.text_field :metatype %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsDocket/app/views/firms/edit.html.erb
<h1>Editing firm</h1>

<%= render 'form' %>

<%= link_to 'Show', @firm %> |
<%= link_to 'Back', firms_path %>

RailsDocket/app/views/firms/index.html.erb
<h1>Listing firms</h1>

<table>
  <tr>
    <th>Metatype</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @firms.each do |firm| %>
  <tr>
    <td><%= firm.metatype %></td>
    <td><%= firm.data %></td>
    <td><%= link_to 'Show', firm %></td>
    <td><%= link_to 'Edit', edit_firm_path(firm) %></td>
    <td><%= link_to 'Destroy', firm, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Firm', new_firm_path %>

RailsDocket/app/views/firms/new.html.erb
<h1>New firm</h1>

<%= render 'form' %>

<%= link_to 'Back', firms_path %>

RailsDocket/app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Metatype:</b>
  <%= @firm.metatype %>
</p>

<p>
  <b>Data:</b>
  <%= @firm.data %>
</p>


<%= link_to 'Edit', edit_firm_path(@firm) %> |
<%= link_to 'Back', firms_path %>