RailsDocket/config/routes.rb
RailsDocket::Application.routes.draw do
  resources :patentcases

  resources :clientcases

  resources :billings

  resources :firms

  resources :caseevents

  resources :cases

  resources :clients

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

RailsDocket/app/models/caseevent.rb
class Caseevent < ActiveRecord::Base
end

RailsDocket/app/controllers/caseevents_controller.rb
class CaseeventsController < ApplicationController
  # GET /caseevents
  # GET /caseevents.json
  def index
    @caseevents = Caseevent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @caseevents }
    end
  end

  # GET /caseevents/1
  # GET /caseevents/1.json
  def show
    @caseevent = Caseevent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @caseevent }
    end
  end

  # GET /caseevents/new
  # GET /caseevents/new.json
  def new
    @caseevent = Caseevent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @caseevent }
    end
  end

  # GET /caseevents/1/edit
  def edit
    @caseevent = Caseevent.find(params[:id])
  end

  # POST /caseevents
  # POST /caseevents.json
  def create
    @caseevent = Caseevent.new(params[:caseevent])

    respond_to do |format|
      if @caseevent.save
        format.html { redirect_to @caseevent, :notice => 'Caseevent was successfully created.' }
        format.json { render :json => @caseevent, :status => :created, :location => @caseevent }
      else
        format.html { render :action => "new" }
        format.json { render :json => @caseevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /caseevents/1
  # PUT /caseevents/1.json
  def update
    @caseevent = Caseevent.find(params[:id])

    respond_to do |format|
      if @caseevent.update_attributes(params[:caseevent])
        format.html { redirect_to @caseevent, :notice => 'Caseevent was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @caseevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /caseevents/1
  # DELETE /caseevents/1.json
  def destroy
    @caseevent = Caseevent.find(params[:id])
    @caseevent.destroy

    respond_to do |format|
      format.html { redirect_to caseevents_url }
      format.json { head :ok }
    end
  end
end

RailsDocket/app/helpers/caseevents_helper.rb
module CaseeventsHelper
end

RailsDocket/app/views/caseevents/_form.html.erb
<%= form_for(@caseevent) do |f| %>
  <% if @caseevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caseevent.errors.count, "error") %> prohibited this caseevent from being saved:</h2>

      <ul>
      <% @caseevent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :case_id %><br />
    <%= f.number_field :case_id %>
  </div>
  <div class="field">
    <%= f.label :eventtype %><br />
    <%= f.text_field :eventtype %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsDocket/app/views/caseevents/edit.html.erb
<h1>Editing caseevent</h1>

<%= render 'form' %>

<%= link_to 'Show', @caseevent %> |
<%= link_to 'Back', caseevents_path %>

RailsDocket/app/views/caseevents/index.html.erb
<h1>Listing caseevents</h1>

<table>
  <tr>
    <th>Case</th>
    <th>Eventtype</th>
    <th>Date</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @caseevents.each do |caseevent| %>
  <tr>
    <td><%= caseevent.case_id %></td>
    <td><%= caseevent.eventtype %></td>
    <td><%= caseevent.date %></td>
    <td><%= caseevent.complete %></td>
    <td><%= link_to 'Show', caseevent %></td>
    <td><%= link_to 'Edit', edit_caseevent_path(caseevent) %></td>
    <td><%= link_to 'Destroy', caseevent, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Caseevent', new_caseevent_path %>

RailsDocket/app/views/caseevents/new.html.erb
<h1>New caseevent</h1>

<%= render 'form' %>

<%= link_to 'Back', caseevents_path %>

RailsDocket/app/views/caseevents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Case:</b>
  <%= @caseevent.case_id %>
</p>

<p>
  <b>Eventtype:</b>
  <%= @caseevent.eventtype %>
</p>

<p>
  <b>Date:</b>
  <%= @caseevent.date %>
</p>

<p>
  <b>Complete:</b>
  <%= @caseevent.complete %>
</p>


<%= link_to 'Edit', edit_caseevent_path(@caseevent) %> |
<%= link_to 'Back', caseevents_path %>