RailsDocket/config/routes.rb
RailsDocket::Application.routes.draw do
  resources :patentcases

  resources :clientcases

  resources :billings

  resources :firms

  resources :caseevents

  resources :cases

  resources :clients

  devise_for :users

  get "home/index"

  root :to => 'home#index'

end

RailsDocket/app/models/billing.rb
class Billing < ActiveRecord::Base
end

RailsDocket/app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @billings }
    end
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
    @billing = Billing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @billing }
    end
  end

  # GET /billings/new
  # GET /billings/new.json
  def new
    @billing = Billing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @billing }
    end
  end

  # GET /billings/1/edit
  def edit
    @billing = Billing.find(params[:id])
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(params[:billing])

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, :notice => 'Billing was successfully created.' }
        format.json { render :json => @billing, :status => :created, :location => @billing }
      else
        format.html { render :action => "new" }
        format.json { render :json => @billing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /billings/1
  # PUT /billings/1.json
  def update
    @billing = Billing.find(params[:id])

    respond_to do |format|
      if @billing.update_attributes(params[:billing])
        format.html { redirect_to @billing, :notice => 'Billing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @billing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing = Billing.find(params[:id])
    @billing.destroy

    respond_to do |format|
      format.html { redirect_to billings_url }
      format.json { head :ok }
    end
  end
end

RailsDocket/app/helpers/billings_helper.rb
module BillingsHelper
end

RailsDocket/app/views/billings/_form.html.erb
<%= form_for(@billing) do |f| %>
  <% if @billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
      <% @billing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :case_id %><br />
    <%= f.number_field :case_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsDocket/app/views/billings/edit.html.erb
<h1>Editing billing</h1>

<%= render 'form' %>

<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

RailsDocket/app/views/billings/index.html.erb
<h1>Listing billings</h1>

<table>
  <tr>
    <th>Case</th>
    <th>Date</th>
    <th>Hours</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @billings.each do |billing| %>
  <tr>
    <td><%= billing.case_id %></td>
    <td><%= billing.date %></td>
    <td><%= billing.hours %></td>
    <td><%= billing.note %></td>
    <td><%= link_to 'Show', billing %></td>
    <td><%= link_to 'Edit', edit_billing_path(billing) %></td>
    <td><%= link_to 'Destroy', billing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Billing', new_billing_path %>

RailsDocket/app/views/billings/new.html.erb
<h1>New billing</h1>

<%= render 'form' %>

<%= link_to 'Back', billings_path %>

RailsDocket/app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Case:</b>
  <%= @billing.case_id %>
</p>

<p>
  <b>Date:</b>
  <%= @billing.date %>
</p>

<p>
  <b>Hours:</b>
  <%= @billing.hours %>
</p>

<p>
  <b>Note:</b>
  <%= @billing.note %>
</p>


<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>